export const clients = [
  {
    id: "1",
    name: "Michael Johnson",
    email: "michael.johnson@email.com",
    phone: "(555) 123-4567",
    company: "Johnson Enterprises",
    status: "Active",
    activeCases: 2,
    totalCases: 3,
    dateAdded: "2024-01-10",
    lastContact: "2024-01-28",
  },
  {
    id: "2",
    name: "Sarah Williams",
    email: "sarah.williams@email.com",
    phone: "(555) 234-5678",
    company: "Williams Family Trust",
    status: "Active",
    activeCases: 1,
    totalCases: 1,
    dateAdded: "2024-01-08",
    lastContact: "2024-01-25",
  },
  {
    id: "3",
    name: "TechCorp Inc.",
    email: "legal@techcorp.com",
    phone: "(555) 345-6789",
    company: "TechCorp Inc.",
    status: "Active",
    activeCases: 1,
    totalCases: 5,
    dateAdded: "2023-12-15",
    lastContact: "2024-01-30",
  },
  {
    id: "4",
    name: "Jennifer Davis",
    email: "jennifer.davis@email.com",
    phone: "(555) 456-7890",
    company: null,
    status: "Inactive",
    activeCases: 0,
    totalCases: 2,
    dateAdded: "2023-11-20",
    lastContact: "2024-01-15",
  },
  {
    id: "5",
    name: "Robert Chen",
    email: "robert.chen@email.com",
    phone: "(555) 567-8901",
    company: "Chen & Associates",
    status: "Active",
    activeCases: 3,
    totalCases: 4,
    dateAdded: "2024-01-05",
    lastContact: "2024-01-29",
  },
];

export const cases = [
  {
    id: "1",
    title: "Johnson vs. Smith",
    client: "Michael Johnson",
    status: "Active",
    type: "Personal Injury",
    category: "Litigation",
    dateCreated: "2024-01-15",
    nextHearing: "2024-02-20",
    pastHearings: [
      { date: "2024-01-25", type: "Initial Hearing", outcome: "Discovery ordered" },
      { date: "2024-02-05", type: "Status Conference", outcome: "Settlement discussed" }
    ],
    description: "Motor vehicle accident case involving rear-end collision",
    attorney: "Johnathan Smith",
  },
  {
    id: "2",
    title: "Estate Planning - Williams",
    client: "Sarah Williams",
    status: "In Review",
    type: "Estate Planning",
    category: "General Advice",
    dateCreated: "2024-01-10",
    nextHearing: null,
    pastHearings: [],
    description: "Comprehensive estate planning including will and trust setup",
    attorney: "Elizabeth Johnson",
  },
  {
    id: "3",
    title: "Corporate Law - TechCorp",
    client: "TechCorp Inc.",
    status: "Active",
    type: "Corporate Law",
    category: "General Advice",
    dateCreated: "2024-01-05",
    nextHearing: "2024-02-15",
    pastHearings: [
      { date: "2024-01-20", type: "Compliance Review", outcome: "Approved" }
    ],
    description: "Contract negotiation and compliance review",
    attorney: "Michael Davis",
  },
  {
    id: "4",
    title: "Divorce Proceedings - Davis",
    client: "Jennifer Davis",
    status: "Pending",
    type: "Family Law",
    category: "Litigation",
    dateCreated: "2024-01-20",
    nextHearing: "2024-02-25",
    pastHearings: [
      { date: "2024-02-10", type: "Custody Hearing", outcome: "Temporary agreement reached" }
    ],
    description: "Uncontested divorce with child custody arrangements",
    attorney: "Sarah Wilson",
  },
  {
    id: "5",
    title: "Contract Dispute - ABC Corp",
    client: "ABC Corporation",
    status: "Concluded",
    type: "Corporate Law",
    category: "Litigation",
    dateCreated: "2023-12-01",
    nextHearing: null,
    pastHearings: [
      { date: "2024-01-15", type: "Mediation", outcome: "Settled" }
    ],
    description: "Contract dispute resolved through mediation",
    attorney: "David Brown",
  },
  {
    id: "6",
    title: "Merger: TechStart & InnovateCo",
    client: "TechStart Inc.",
    status: "Active",
    type: "Mergers & Acquisitions",
    category: "Merger or Acquisition",
    dateCreated: "2024-01-08",
    nextHearing: "2024-03-10",
    pastHearings: [
      { date: "2024-02-01", type: "Due Diligence Review", outcome: "Completed" }
    ],
    description: "Advising on merger between two tech startups",
    attorney: "Robert Lee",
  },
  {
    id: "7",
    title: "Acquisition: RetailChain Buyout",
    client: "RetailChain LLC",
    status: "In Review",
    type: "Mergers & Acquisitions",
    category: "Merger or Acquisition",
    dateCreated: "2024-01-12",
    nextHearing: null,
    pastHearings: [],
    description: "Due diligence for acquisition of smaller retail chain",
    attorney: "Anna Martinez",
  },
  {
    id: "8",
    title: "Patent Infringement - GadgetCorp",
    client: "GadgetCorp Ltd.",
    status: "Active",
    type: "Intellectual Property",
    category: "Litigation",
    dateCreated: "2024-01-18",
    nextHearing: "2024-02-28",
    pastHearings: [
      { date: "2024-02-10", type: "Preliminary Hearing", outcome: "Evidence submitted" }
    ],
    description: "Defending against patent infringement lawsuit",
    attorney: "Kevin Wong",
  },
  {
    id: "9",
    title: "Will and Trust Setup - Thompson",
    client: "Robert Thompson",
    status: "Pending",
    type: "Estate Planning",
    category: "General Advice",
    dateCreated: "2024-01-22",
    nextHearing: null,
    pastHearings: [],
    description: "Drafting last will and testament with trust provisions",
    attorney: "Lisa Chen",
  },
  {
    id: "10",
    title: "Hostile Takeover Defense - MegaCorp",
    client: "MegaCorp Industries",
    status: "Active",
    type: "Corporate Defense",
    category: "Merger or Acquisition",
    dateCreated: "2024-01-25",
    nextHearing: "2024-03-05",
    pastHearings: [
      { date: "2024-02-15", type: "Board Meeting", outcome: "Strategy approved" }
    ],
    description: "Advising board on defense strategies against hostile takeover",
    attorney: "James Parker",
  },
  {
    id: "11",
    title: "Employment Discrimination Suit",
    client: "Maria Gonzalez",
    status: "In Review",
    type: "Employment Law",
    category: "Litigation",
    dateCreated: "2024-01-28",
    nextHearing: "2024-02-22",
    pastHearings: [
      { date: "2024-02-05", type: "Deposition", outcome: "Completed" }
    ],
    description: "Wrongful termination and discrimination claim",
    attorney: "Sophia Patel",
  },
  {
    id: "12",
    title: "Business Formation - StartupXYZ",
    client: "StartupXYZ",
    status: "Concluded",
    type: "Business Law",
    category: "General Advice",
    dateCreated: "2023-11-15",
    nextHearing: null,
    pastHearings: [],
    description: "Incorporation and initial compliance setup for new startup",
    attorney: "David Kim",
  },
  {
    id: "13",
    title: "Joint Venture Agreement - GlobalTrade",
    client: "GlobalTrade Partners",
    status: "Active",
    type: "International Business",
    category: "Merger or Acquisition",
    dateCreated: "2024-02-01",
    nextHearing: "2024-03-15",
    pastHearings: [
      { date: "2024-02-20", type: "Negotiation Meeting", outcome: "Terms agreed" }
    ],
    description: "Negotiating joint venture terms between US and European firms",
    attorney: "Emma Taylor",
  },
  {
    id: "14",
    title: "Medical Malpractice Claim",
    client: "Thomas Anderson",
    status: "Pending",
    type: "Medical Malpractice",
    category: "Litigation",
    dateCreated: "2024-02-05",
    nextHearing: "2024-03-20",
    pastHearings: [
      { date: "2024-02-25", type: "Expert Witness Deposition", outcome: "Scheduled" }
    ],
    description: "Surgical error resulting in permanent injury",
    attorney: "Rachel Green",
  },
  {
    id: "15",
    title: "Tax Planning Consultation - HighNetWorth",
    client: "HighNetWorth Family Office",
    status: "In Review",
    type: "Tax Law",
    category: "General Advice",
    dateCreated: "2024-02-08",
    nextHearing: null,
    pastHearings: [],
    description: "Comprehensive tax planning and estate tax minimization strategies",
    attorney: "Mark Johnson",
  },
];

export const invoices = [
  {
    id: "INV-001",
    client: "Michael Johnson",
    case: "Johnson vs. Smith",
    amount: 5500.00,
    date: "2024-01-15",
    dueDate: "2024-02-15",
    status: "paid",
    description: "Legal services for personal injury case",
    hoursWorked: 22,
    hourlyRate: 250,
  },
  {
    id: "INV-002",
    client: "Sarah Williams",
    case: "Williams Estate Planning",
    amount: 3200.00,
    date: "2024-01-20",
    dueDate: "2024-02-20",
    status: "pending-approval",
    description: "Estate planning and will preparation",
    hoursWorked: 16,
    hourlyRate: 200,
  },
  {
    id: "INV-003",
    client: "TechCorp Inc.",
    case: "Corporate Legal Review",
    amount: 8750.00,
    date: "2024-01-25",
    dueDate: "2024-02-25",
    status: "overdue",
    description: "Contract review and legal consultation",
    hoursWorked: 35,
    hourlyRate: 250,
  },
  {
    id: "INV-004",
    client: "Jennifer Davis",
    case: "Davis Divorce Proceedings",
    amount: 4200.00,
    date: "2024-01-28",
    dueDate: "2024-02-28",
    status: "sent",
    description: "Family law services and court representation",
    hoursWorked: 21,
    hourlyRate: 200,
  },
  {
    id: "INV-005",
    client: "Robert Chen",
    case: "Chen Business Formation",
    amount: 2800.00,
    date: "2024-01-30",
    dueDate: "2024-03-01",
    status: "draft",
    description: "Business formation and incorporation services",
    hoursWorked: 14,
    hourlyRate: 200,
  },
  {
    id: "INV-006",
    client: "Emma Thompson",
    case: "Thompson IP Litigation",
    amount: 6800.00,
    date: "2024-01-18",
    dueDate: "2024-02-18",
    status: "paid",
    description: "Patent infringement defense",
    hoursWorked: 27,
    hourlyRate: 250,
  },
  {
    id: "INV-007",
    client: "Global Consulting Ltd",
    case: "Contract Dispute Resolution",
    amount: 9500.00,
    date: "2024-01-22",
    dueDate: "2024-02-22",
    status: "sent",
    description: "Commercial litigation services",
    hoursWorked: 38,
    hourlyRate: 250
  },
];

export const timeEntries = [
  {
    id: "1",
    date: "2024-01-30",
    client: "Michael Johnson",
    case: "Johnson vs. Smith",
    description: "Review medical records and prepare case summary",
    hours: 3.5,
    rate: 250,
    amount: 875.00,
    billable: true,
    timekeeper: "Johnathan Smith",
  },
  {
    id: "2",
    date: "2024-01-30",
    client: "Sarah Williams",
    case: "Williams Estate Planning",
    description: "Draft will and trust documents",
    hours: 2.0,
    rate: 200,
    amount: 400.00,
    billable: true,
    timekeeper: "Elizabeth Johnson",
  },
  {
    id: "3",
    date: "2024-01-29",
    client: "TechCorp Inc.",
    case: "Corporate Legal Review",
    description: "Contract negotiation meeting",
    hours: 4.0,
    rate: 250,
    amount: 1000.00,
    billable: true,
    timekeeper: "Michael Davis",
  },
  {
    id: "4",
    date: "2024-01-29",
    client: "Jennifer Davis",
    case: "Davis Divorce Proceedings",
    description: "Court hearing preparation",
    hours: 2.5,
    rate: 200,
    amount: 500.00,
    billable: true,
    timekeeper: "Sarah Wilson",
  },
];
